http:
  routers:
    pushav-router:
      rule: "PathPrefix(`/pushav`)"
      service: pushav-service
      middlewares:
        - pushav-stripprefix
  services:
    pushav-service:
      loadBalancer:
        servers:
          - url: "https://172.17.0.1:1234"
  middlewares:
    pushav-stripprefix:
      stripPrefix:
        prefixes:
          - "/pushav"
