"""Add Project Config

Revision ID: 028ec0c3c704
Revises: 4b5532b0ac1e
Create Date: 2022-04-15 14:54:43.428193

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "028ec0c3c704"
down_revision = "4b5532b0ac1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("config", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "config")
    # ### end Alembic commands ###
