"""Make TestRunConfig Optional

Revision ID: 079dfe8e3e03
Revises: 31f2da69d8c4
Create Date: 2021-06-24 10:05:23.054043

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "079dfe8e3e03"
down_revision = "31f2da69d8c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "testrunexecution",
        "test_run_config_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "testrunexecution",
        "test_run_config_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
