"""Adding PICS JSON to Project

Revision ID: 489ef0771cbe
Revises: 028ec0c3c704
Create Date: 2022-05-23 10:09:33.482226

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "489ef0771cbe"
down_revision = "028ec0c3c704"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("pics", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "pics")
    # ### end Alembic commands ###
