"""Added Thread Project Config

Revision ID: 621cc7fec168
Revises: d125c14ea922
Create Date: 2021-07-26 19:18:16.148796

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "621cc7fec168"
down_revision = "d125c14ea922"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("thread_channel", sa.String(), nullable=True))
    op.add_column("project", sa.Column("thread_extpanid", sa.String(), nullable=True))
    op.add_column("project", sa.Column("thread_masterkey", sa.String(), nullable=True))
    op.add_column(
        "project", sa.Column("thread_networkname", sa.String(), nullable=True)
    )
    op.add_column(
        "project", sa.Column("thread_on_mesh_prefix", sa.String(), nullable=True)
    )
    op.add_column("project", sa.Column("thread_panid", sa.String(), nullable=True))
    op.add_column(
        "project", sa.Column("thread_rcp_serial_path", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "thread_rcp_serial_path")
    op.drop_column("project", "thread_panid")
    op.drop_column("project", "thread_on_mesh_prefix")
    op.drop_column("project", "thread_networkname")
    op.drop_column("project", "thread_masterkey")
    op.drop_column("project", "thread_extpanid")
    op.drop_column("project", "thread_channel")
    # ### end Alembic commands ###
