"""Make project mandatory for TestRunExecution

Revision ID: 6494682dab86
Revises: 4183bcf568f2
Create Date: 2021-07-26 20:34:56.001678

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6494682dab86"
down_revision = "4183bcf568f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "testrunexecution", "project_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "testrunexecution", "project_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
