"""Added archive support Project, TestRunExecution

Revision ID: 66f5fdf75be8
Revises: f5af3855be39
Create Date: 2022-01-19 09:38:22.325528

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "66f5fdf75be8"
down_revision = "f5af3855be39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("archived_at", sa.DateTime(), nullable=True))
    op.add_column(
        "testrunexecution", sa.Column("archived_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("testrunexecution", "archived_at")
    op.drop_column("project", "archived_at")
    # ### end Alembic commands ###
