"""Added test run config

Revision ID: 72989eaa90f6
Revises: 8ad40d9f3ac1
Create Date: 2020-10-30 21:30:47.689556

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "72989eaa90f6"
down_revision = "8ad40d9f3ac1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "testrunconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("dut_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("selected_test_cases", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_testrunconfig")),
    )
    op.create_index(op.f("ix_testrunconfig_id"), "testrunconfig", ["id"], unique=False)
    op.add_column(
        "testrunexecution",
        sa.Column("test_run_config_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_testrunexecution_test_run_config_id_testrunconfig"),
        "testrunexecution",
        "testrunconfig",
        ["test_run_config_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_testrunexecution_test_run_config_id_testrunconfig"),
        "testrunexecution",
        type_="foreignkey",
    )
    op.drop_column("testrunexecution", "test_run_config_id")
    op.drop_index(op.f("ix_testrunconfig_id"), table_name="testrunconfig")
    op.drop_table("testrunconfig")
    # ### end Alembic commands ###
