"""Added log to run

Revision ID: 94d307a738ba
Revises: ff250c32cf31
Create Date: 2021-04-20 14:41:08.377934

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "94d307a738ba"
down_revision = "ff250c32cf31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "testrunexecution",
        sa.Column("log", sa.JSON(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("testrunexecution", "log")
    # ### end Alembic commands ###
