"""import/export feature

Revision ID: 9996326cbd1d
Revises: 5ad169ab8749
Create Date: 2023-05-22 16:35:16.372400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9996326cbd1d"
down_revision = "5ad169ab8749"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "testrunexecution", sa.Column("imported_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("testrunexecution", "imported_at")
    # ### end Alembic commands ###
