"""Add Operator

Revision ID: f5af3855be39
Revises: 6494682dab86
Create Date: 2021-08-19 21:18:16.371500

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f5af3855be39"
down_revision = "6494682dab86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operator",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator")),
    )
    op.create_index(op.f("ix_operator_id"), "operator", ["id"], unique=False)
    op.add_column(
        "testrunexecution", sa.Column("operator_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_testrunexecution_operator_id_operator"),
        "testrunexecution",
        "operator",
        ["operator_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_testrunexecution_operator_id_operator"),
        "testrunexecution",
        type_="foreignkey",
    )
    op.drop_column("testrunexecution", "operator_id")
    op.drop_index(op.f("ix_operator_id"), table_name="operator")
    op.drop_table("operator")
    # ### end Alembic commands ###
