"""Adding failure column to Test Step Execution

Revision ID: ff250c32cf31
Revises: 136e7b39e9e8
Create Date: 2021-02-18 17:26:32.455904

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ff250c32cf31"
down_revision = "136e7b39e9e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teststepexecution",
        sa.Column("failures", sa.ARRAY(sa.String(), dimensions=1), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teststepexecution", "failures")
    # ### end Alembic commands ###
