name: npm linting 
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      
jobs: 
  build:
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v1
    - name: setup-node
      uses: actions/setup-python@v1
      with:
        node-version: 14.x
    - name: Install Dependencies
      run: |
        npm install
    - name: Code Linting
      run: |
        npm run lint
